name: 'Prepare build'
description: 'Prepare build'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '18.18.0'
        cache: 'yarn'
    - run: yarn --frozen-lockfile
      shell: bash
