name: 'Docker publish'
description: 'Build and publish docker image'
inputs:
  docker_hub_scope:
    description: 'Docker Hub scope'
    required: true
  username:
    description: 'Docker Hub username'
    required: true
  token:
    description: 'Docker Hub token'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: ./.github/prepare-build
    - run: yarn build
      shell: bash
    - uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.token }}
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.docker_hub_scope }}/${{ github.event.repository.name }}
    - uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
